language: java
jdk:
  - oraclejdk8

notifications:
  email: false

sudo: required

services:
- docker
- postgresql

before_install:
- docker pull sath89/oracle-xe-11g
- docker build -t sql2o-oracle ./extensions/oracle
- docker run -d --rm -p 1521:1521 --name=sql2o-oracle-xe-11g sql2o-oracle

before_script:
- psql -c "CREATE USER test WITH PASSWORD 'testtest';" -U postgres
- psql -c "CREATE DATABASE testdb WITH OWNER test;" -U postgres

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true
- mvn compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V -pl core,extensions,extensions/db2,extensions/postgres

script:
- mvn test -B -V -pl core,extensions,extensions/postgres,extensions/db2
- mvn clean cobertura:cobertura -Dcobertura.report.format=xml

after_script:
- docker kill sql2o-oracle-xe-11g

after_success:
  - sonar:sonar  -Dsonar.organization=ivyxjc-github  -Dsonar.login=$ivyxjcSonar  -Dsonar.host.url=https://sonarcloud.io
  - bash <(curl -s https://codecov.io/bash)
